image: docker:latest

stages:
  - build
  - release

services:
  - docker:dind


before_script:
  - time_stamp=`date +"%Y%m%d"`
  - if [ -z "${CI_COMMIT_TAG}" ]; then APP_VERSION="${CI_COMMIT_SHA}-${time_stamp}"; else APP_VERSION="${CI_COMMIT_TAG}-${time_stamp}"; fi
  - echo "gitlab_predefined_variables:" $CI_JOB_ID \"$CI_JOB_NAME\" $CI_PROJECT_ID \"$CI_PROJECT_NAME\" $GITLAB_USER_ID \"$GITLAB_USER_NAME\"
  - env

user:
  stage: build
  variables:
    BRANCH: dev
    DOCKER_REP: ccr.ccs.tencentyun.com/chaunce/chaunce
    DOCKER_USER: 100000633927
    DOCKER_PWD: net111111
    IMAGE_NAME: user-api
    COMMIT_TIME: $(git show -s --format=%ct $CI_COMMIT_SHA)
  script:
    - echo $APP_VERSION
    - docker build -f ./Dockerfile -t ${IMAGE_NAME}:DEV-${APP_VERSION} .
    # - image_id=`grep "Successfully built" docker_log|awk '{print $NF}'`
    - docker login  -u ${DOCKER_USER} -p ${DOCKER_PWD} ${DOCKER_REP}
    - docker tag ${IMAGE_NAME}:DEV-${APP_VERSION} ${DOCKER_REP}/${IMAGE_NAME}:DEV-${APP_VERSION}
    - docker push ${DOCKER_REP}/${IMAGE_NAME}:DEV-${APP_VERSION}
    - docker rmi $(docker images -f "dangling=true" -q) 
    - docker rmi -f ${IMAGE_NAME}:DEV-${APP_VERSION}
    - docker rmi -f ${DOCKER_REP}/${IMAGE_NAME}:DEV-${APP_VERSION}
